Fix pep8 for app/models.py
Fixed

```
app/models.py:3:1: F401 'request' imported but unused
app/models.py:7:1: F811 redefinition of unused 'current_app' from line 3
app/models.py:12:1: F401 'SQLAlchemy' imported but unused
app/models.py:17:1: F401 'bleach' imported but unused
app/models.py:22:1: E302 expected 2 blank lines, found 1
app/models.py:38:1: E302 expected 2 blank lines, found 1
app/models.py:48:1: E302 expected 2 blank lines, found 1
app/models.py:50:43: E251 unexpected spaces around keyword / parameter
equals
app/models.py:50:45: E251 unexpected spaces around keyword / parameter
equals
app/models.py:72:17: E128 continuation line under-indented for visual
indent
app/models.py:73:17: E128 continuation line under-indented for visual
indent
app/models.py:74:17: E128 continuation line under-indented for visual
indent
app/models.py:93:61: E231 missing whitespace after ','
app/models.py:93:80: E501 line too long (84 > 79 characters)
app/models.py:165:13: E128 continuation line under-indented for visual
indent
app/models.py:165:23: E251 unexpected spaces around keyword / parameter
equals
app/models.py:165:25: E251 unexpected spaces around keyword / parameter
equals
app/models.py:190:1: E302 expected 2 blank lines, found 1
app/models.py:191:1: W293 blank line contains whitespace
app/models.py:200:1: E302 expected 2 blank lines, found 1
app/models.py:203:1: E302 expected 2 blank lines, found 1
app/models.py:215:80: E501 line too long (91 > 79 characters)
app/models.py:255:80: E501 line too long (90 > 79 characters)
app/models.py:270:32: E712 comparison to False should be 'if cond is
False:' or 'if not cond:'
app/models.py:274:1: E302 expected 2 blank lines, found 1
```

Addresses https://github.com/levlaz/braindump/issues/87